services:
  pgvector:
    image: "pgvector/pgvector:pg16"
    environment:
      - POSTGRES_DB=faq-coffee
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - VECTOR_STORE_TYPE=pgVector
    labels:
      - org.springframework.boot.service-connection=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U admin -d vector_store"
      interval: 2s
      timeout: 20s
      retries: 10
